In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('us-simmsfishing.csv')

In [4]:
df

,SKU,Name,Categories,Regular price,Sale price,Attribute 1 value(s),Attribute 1 name,Images,ImagesUrl,Tags,PageUrl,Description
0,SK0000001-US,Selway Life Vest,Hot-selling,250.0,62.5,color#Slate~ Size#XS/S|M/L|XL/2XL,mycustom,"""https://cdn.staticsaa.com/uploads/68512/cart/...",NaN,NaN,https://us-simmsfishing.shop/products/selway-l...,"<div> <p>The ultimate life vest for anglers, t..."
1,SK0000002-US,M‘s G3 Guide Waders - Bootfoot - Vibram Sole,New Arrival,600.0,120.0,color#Gunmetal~ Size#S 08|M 09|M 10|M 11|L 1...,mycustom,"""https://cdn.staticsaa.com/uploads/68512/cart/...",NaN,NaN,https://us-simmsfishing.shop/products/m-s-g3-g...,<div> <p>Built for anglers who demand the utmo...
2,SK0000003-US,"Wading Belt - 2""",Hot-selling,40.0,12.0,color#Regiment Camo Carbon|Regiment Camo Olive...,mycustom,"""https://cdn.staticsaa.com/uploads/68512/cart/...",NaN,NaN,https://us-simmsfishing.shop/products/wading-b...,<div> <p>No two anglers are built quite the sa...
3,SK0000004-US,M‘s G4 PRO® Wading Jacket,Today’s Special,500.0,100.0,Color#Slate~ Size#S|M|L|XL|2XL,mycustom,"""https://cdn.staticsaa.com/uploads/68512/cart/...",NaN,NaN,https://us-simmsfishing.shop/products/m-s-g4-p...,<p>The highest-tech wading jacket on the water...
4,SK0000005-US,M‘s Freestone Z Bootfoot Waders - Rubber Sole,Hot-selling,580.0,116.0,color#Loden~ Size#S 08|M 09|M 10|M 11|L 10|L...,mycustom,"""https://cdn.staticsaa.com/uploads/68512/cart/...",NaN,NaN,https://us-simmsfishing.shop/products/m-s-free...,"<div> <p>The ultimate cold-weather wader, the ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
220,SK0000221-US,Superlight Sunshield Cap,Flash Deal,35.0,10.5,color#Sterling|Regiment Camo Olive Drab~ Siz...,mycustom,"""https://cdn.staticsaa.com/uploads/68512/cart/...",NaN,NaN,https://us-simmsfishing.shop/products/superlig...,<div> <div> <p>Spot more fish and reduce glare...
221,SK0000222-US,Simms ID Trucker,Editor's Pick,30.0,9.0,color#Dark Stone|Heather Grey|Neptune|Riparian...,mycustom,"""https://cdn.staticsaa.com/uploads/68512/cart/...",NaN,NaN,https://us-simmsfishing.shop/products/simms-id...,<div> <div> <p>Simms ID Trucker</p> <br><ul><l...
222,SK0000223-US,Single Haul Cap,Editor's Pick,30.0,9.0,color#Cinder|Woodland Camo|Simms Orange|Admira...,mycustom,"""https://cdn.staticsaa.com/uploads/68512/cart/...",NaN,NaN,https://us-simmsfishing.shop/products/single-h...,<div> <p>The trusty and extra lucky cotton-twi...
223,SK0000224-US,Big Sky Wool Beanie,Promotion,40.0,12.0,color#Carbon|Simms Orange~ Size#One Size,mycustom,"""https://cdn.staticsaa.com/uploads/68512/cart/...",NaN,NaN,https://us-simmsfishing.shop/products/big-sky-...,"<div> <p>High seas to summit vistas, our wool ..."
224,SK0000225-US,Everyday Beanie,Best Value,35.0,10.5,color#Carbon|Black|Carbon Stripe|Graphite|Midn...,mycustom,"""https://cdn.staticsaa.com/uploads/68512/cart/...",NaN,NaN,https://us-simmsfishing.shop/products/everyday...,<div> <div> <p>The most trusted go-anywhere be...

In [5]:
dft=pd.read_excel("products_import_template.xlsx")

In [6]:
dft.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 34 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   商品ID            1 non-null      object
 1   创建时间            1 non-null      object
 2   商品标题*           6 non-null      object
 3   商品属性*           6 non-null      object
 4   商品类型            3 non-null      object
 5   商品副标题           1 non-null      object
 6   商品描述            1 non-null      object
 7   简短描述            1 non-null      object
 8   内部商品名           1 non-null      object
 9   SEO标题           3 non-null      object
 10  SEO描述           3 non-null      object
 11  SEO URL Handle  3 non-null      object
 12  SEO关键词          1 non-null      object
 13  商品上架            3 non-null      object
 14  商品收税            3 non-null      object
 15  商品spu           3 non-null      object
 16  虚拟销量值           3 non-null      object
 17  跟踪库存            3 non-null      object
 18  库存规则*           3 non-null      object
 19  专辑名称            1 non-null      object
 20  标签              3 non-null      object
 21  供应商名称           3 non-null      object
 22  款式1             5 non-null      object
 23  款式2             1 non-null      object
 24  款式3             1 non-null      object
 25  商品售价*           5 non-null      object
 26  商品原价            5 non-null      object
 27  商品SKU           5 non-null      object
 28  商品重量(kg)        5 non-null      object
 29  商品条形码           1 non-null      object
 30  商品库存            5 non-null      object
 31  变体备注1           1 non-null      object
 32  变体备注2           1 non-null      object
 33  商品图片*           3 non-null      object
dtypes: object(34)
memory usage: 1.7+ KB

In [8]:
star_col=[col for col in dft.columns if '*' in col]

In [ ]:


# 查看前两行数据
note_row = dft.head(1)

# 竖着打印
for column in note_row.columns:
    print(f"{column}: {note_row[column].tolist()}")

商品ID: ['（此行导入时不可删除 ）商品 ID 是系统生成的唯一标识符，新增商品无需填写']
创建时间: ['创建时间的时区为当前店铺设置的时区']
商品标题*: ['最多250字符(同一商品的子款式标题与商品标题需一致，且中间请勿插入其他商品)']
商品属性*: ['"1.多款式商品：同一个商品的首行标题填入「M」（商品主体)；同一个商品的非首行标题填入「P」(子款式)；\n2.单一款式商品（Single）：填入「S」"']
商品类型: ['最多60字符']
商品副标题: ['最多250字符']
商品描述: ['上传不带样式，若需要样式，则输入html代码']
简短描述: ['最多2000字符']
内部商品名: ['最多250字符']
SEO标题: ['最多511字符']
SEO描述: ['最多20字符']
SEO URL Handle: ['最多支持输入255字符（SEO URL handle只对SEO URL的「URL参数」部分进行更改，即“products/”后的内容，如：products/「URL参数」）']
SEO关键词: ['多个关键词请用「英文逗号」隔开']
商品上架: ['「Y」:上架状态\n「N」:下架状态\n默认为「N」']
商品收税: ['「Y」:需要\n「N」:不需要 \n默认为「N」']
商品spu: ['最多60字符']
虚拟销量值: ['最多输入六位数的自然数']
跟踪库存: ['「Y」:跟踪\n「N」:不跟踪\n默认为「N」']
库存规则*: ['「1」库存为0时不允许购买\n「2」库存为0时允许购买\n「3」库存为0时自动下架']
专辑名称: ['请填入已创建的手动专辑名称；多个专辑请用「英文逗号」隔开']
标签: ['最多输入250个标签，每个不得超过255字符，多个标签请用「英文逗号」隔开']
供应商名称: ['最多100字符']
款式1: ['最多63字符']
款式2: ['最多63字符']
款式3: ['最多63字符']
商品售价*: ['最多输入9位正整数，2位小数']
商品原价: ['最多输入9位正整数，2位小数']
商品SKU: ['最多511字符']
商品重量(kg): ['最多输入9位正整数，4位小数']
商品条形码: ['最多63字符']
商品库存: ['最多输入7位整数']
变体备注1: ['最多512字符']
变体备注2: ['最多512字符']
商品图片*: ['1.商品属性为M(商品主体)与S(单一款式商品)的行都必须至少填入一个图片URL，支持填多个URL并用「英文逗号」隔开，默认填入的首个URL为商品主图URL\n2.商品属性为P(子款式)的行仅支持一个URL，填入多个时默认导入第一个，若不填入，则默认不需要图片\n3.同一商品的部分子款式上传图片，则其余款式也需要上传，否则默认填入商品主图']

In [22]:
#查看模板字段注释说明
x=dft.loc[0]
x

商品ID                         （此行导入时不可删除 ）商品 ID 是系统生成的唯一标识符，新增商品无需填写
创建时间                                              创建时间的时区为当前店铺设置的时区
商品标题*                       最多250字符(同一商品的子款式标题与商品标题需一致，且中间请勿插入其他商品)
商品属性*             "1.多款式商品：同一个商品的首行标题填入「M」（商品主体)；同一个商品的非首行标题填入「P...
商品类型                                                         最多60字符
商品副标题                                                       最多250字符
商品描述                                         上传不带样式，若需要样式，则输入html代码
简短描述                                                       最多2000字符
内部商品名                                                       最多250字符
SEO标题                                                       最多511字符
SEO描述                                                        最多20字符
SEO URL Handle    最多支持输入255字符（SEO URL handle只对SEO URL的「URL参数」部分进...
SEO关键词                                              多个关键词请用「英文逗号」隔开
商品上架                                     「Y」:上架状态\n「N」:下架状态\n默认为「N」
商品收税                                       「Y」:需要\n「N」:不需要 \n默认为「N」
商品spu                                                        最多60字符
虚拟销量值                                                   最多输入六位数的自然数
跟踪库存                                        「Y」:跟踪\n「N」:不跟踪\n默认为「N」
库存规则*                     「1」库存为0时不允许购买\n「2」库存为0时允许购买\n「3」库存为0时自动下架
专辑名称                                   请填入已创建的手动专辑名称；多个专辑请用「英文逗号」隔开
标签                            最多输入250个标签，每个不得超过255字符，多个标签请用「英文逗号」隔开
供应商名称                                                       最多100字符
款式1                                                          最多63字符
款式2                                                          最多63字符
款式3                                                          最多63字符
商品售价*                                                最多输入9位正整数，2位小数
商品原价                                                 最多输入9位正整数，2位小数
商品SKU                                                       最多511字符
商品重量(kg)                                             最多输入9位正整数，4位小数
商品条形码                                                        最多63字符
商品库存                                                       最多输入7位整数
变体备注1                                                       最多512字符
变体备注2                                                       最多512字符
商品图片*             1.商品属性为M(商品主体)与S(单一款式商品)的行都必须至少填入一个图片URL，支持填多个...
Name: 0, dtype: object

In [21]:
dft.loc[0,star_col]

商品标题*              最多250字符(同一商品的子款式标题与商品标题需一致，且中间请勿插入其他商品)
商品属性*    "1.多款式商品：同一个商品的首行标题填入「M」（商品主体)；同一个商品的非首行标题填入「P...
库存规则*            「1」库存为0时不允许购买\n「2」库存为0时允许购买\n「3」库存为0时自动下架
商品售价*                                       最多输入9位正整数，2位小数
商品图片*    1.商品属性为M(商品主体)与S(单一款式商品)的行都必须至少填入一个图片URL，支持填多个...
Name: 0, dtype: object

In [23]:
df[1:5]

,SKU,Name,Categories,Regular price,Sale price,Attribute 1 value(s),Attribute 1 name,Images,ImagesUrl,Tags,PageUrl,Description
1,SK0000002-US,M‘s G3 Guide Waders - Bootfoot - Vibram Sole,New Arrival,600.0,120.0,color#Gunmetal~ Size#S 08|M 09|M 10|M 11|L 1...,mycustom,"""https://cdn.staticsaa.com/uploads/68512/cart/...",NaN,NaN,https://us-simmsfishing.shop/products/m-s-g3-g...,<div> <p>Built for anglers who demand the utmo...
2,SK0000003-US,"Wading Belt - 2""",Hot-selling,40.0,12.0,color#Regiment Camo Carbon|Regiment Camo Olive...,mycustom,"""https://cdn.staticsaa.com/uploads/68512/cart/...",NaN,NaN,https://us-simmsfishing.shop/products/wading-b...,<div> <p>No two anglers are built quite the sa...
3,SK0000004-US,M‘s G4 PRO® Wading Jacket,Today’s Special,500.0,100.0,Color#Slate~ Size#S|M|L|XL|2XL,mycustom,"""https://cdn.staticsaa.com/uploads/68512/cart/...",NaN,NaN,https://us-simmsfishing.shop/products/m-s-g4-p...,<p>The highest-tech wading jacket on the water...
4,SK0000005-US,M‘s Freestone Z Bootfoot Waders - Rubber Sole,Hot-selling,580.0,116.0,color#Loden~ Size#S 08|M 09|M 10|M 11|L 10|L...,mycustom,"""https://cdn.staticsaa.com/uploads/68512/cart/...",NaN,NaN,https://us-simmsfishing.shop/products/m-s-free...,"<div> <p>The ultimate cold-weather wader, the ..."

In [24]:
df[['Name',"SKU"]]

                                              Name           SKU
0                                 Selway Life Vest  SK0000001-US
1     M‘s G3 Guide Waders - Bootfoot - Vibram Sole  SK0000002-US
2                                 Wading Belt - 2"  SK0000003-US
3                        M‘s G4 PRO® Wading Jacket  SK0000004-US
4    M‘s Freestone Z Bootfoot Waders - Rubber Sole  SK0000005-US
..                                             ...           ...
220                       Superlight Sunshield Cap  SK0000221-US
221                               Simms ID Trucker  SK0000222-US
222                                Single Haul Cap  SK0000223-US
223                            Big Sky Wool Beanie  SK0000224-US
224                                Everyday Beanie  SK0000225-US

[225 rows x 2 columns]

In [1]:
import pandas as pd

# 创建示例DataFrame
data = {
    '姓名': ['张三', '李四', '王五', '赵六', '钱七'],
    '年龄': [25, 30, 35, 28, 32],
    '城市': ['北京', '上海', '广州', '深圳', '北京'],
    '薪资': [15000, 20000, 25000, 18000, 22000]
}
df = pd.DataFrame(data)

In [4]:
df

   姓名  年龄  城市     薪资
0  张三  25  北京  15000
1  李四  30  上海  20000
2  王五  35  广州  25000
3  赵六  28  深圳  18000
4  钱七  32  北京  22000

In [9]:
df[1:3]

   姓名  年龄  城市     薪资
1  李四  30  上海  20000
2  王五  35  广州  25000

In [5]:
df.loc[2]

姓名       王五
年龄       35
城市       广州
薪资    25000
Name: 2, dtype: object

In [6]:
df['年龄']

0    25
1    30
2    35
3    28
4    32
Name: 年龄, dtype: int64